export enum TransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT'
}

export enum TrxLogType {
  DEPOSIT = 'DEPOSIT', // FUND WALLET
  WITHDRAW = 'WITHDRAW', // WITHDRAW FUNDS
  TRANSFER = 'TRANSFER' // TRANSFER FUNDS BETWEEN ACCOUNTS
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING_REALHAUS = 'PENDING_REALHAUS',
  PENDING_VENDOR = 'PENDING_VENDOR'
}
