export enum TransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  OTHER = 'OTHER',
}

export enum TrxLogType {
  PAYMENT = 'PAYMENT', // MAKE A PAYMENT
  WITHDRAW = 'WITHDRAW', // WITHDRAW FUNDS
  TRANSFER = 'TRANSFER', // TRANSFER FUNDS BETWEEN ACCOUNTS
  REFUND = 'REFUND', // PAYMENT REFUND
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING_REALHAUS = 'PENDING_REALHAUS',
  PENDING_VENDOR = 'PENDING_VENDOR',
}
